### ISSUE TITLE
From network to datacenter at FDSN

### ISSUE THREAD

**Issue by vpet98** [EIDA/find-net-board#1]
I think there is no way to go from the networks of https://www.fdsn.org/networks/ list to the datacenter that each one belongs to.

Neither the API https://www.fdsn.org/ws/networks/ nor the datacite information of each network provide a datacenter identifier that leads to some 1-1 relation to the datacenters API https://www.fdsn.org/ws/datacenters/

So how to get the StationXML metadata for each network without knowing its datacenter?

**Comment by jschaeff** [comment]
You have to link the network code + startyear from https://www.fdsn.org/networks/  registry to https://www.fdsn.org/ws/datacenters/1/query?includedatasets=true

go down to .datacenters[].repositories[].datasets[] filter on the networks where the "priority" == 1 only.

Link them with .datacenters[].name  and .datacenters[].services[]

you will get everything.
