### ISSUE TITLE
Adopt the new network code from Source Identifier

### ISSUE THREAD

**Issue by javiquinte** [EIDA/find-net-board#13]
For temporary networks, you could include the start year in the code.

https://docs.fdsn.org/projects/source-identifiers/en/v1.0/network-codes.html#temporary-network-code-convention

**Comment by vpet98** [comment]
Can I assume that a network is temporary _if and only if_ its code is two characters in length with the first character being a digit (0-9) or one of the letters X, Y or Z?

**Comment by javiquinte** [comment]
Yes, you can. However, forget the two characters limitation. Only the first character is important. The old (current) approach is a 2-chars code, but in the near future this will be a 6, 7, or 8 chars, being the last 4 the starting year.

> <1-4 characters><4-digit start year>
