### ISSUE TITLE
Network start year may not match

### ISSUE THREAD

**Issue by jschaeff** [EIDA/find-net-board#2]
Sometimes, in the routing information (the fdsn datacenters API), the starting year of a network may not match the one in the FDS networks API.

A network in the routing is indentified if it's routing startyear is inside then network startyear and endyear.

routing_net_code == fdsn_net_code and routing_net_start >= fdsn_net_start and routing_net_start <= fdsn_net_end

**Comment by vpet98** [comment]
Taken into account
