### ISSUE TITLE
Restrictions policy and "rightsList" field

### ISSUE THREAD

**Issue by vpet98** [EIDA/find-net-board#3]
In the datacite of a network the "rightsList" field does not take predefined values from which a piece of code could decide if network is open or not.

Some times this field is even empty, like in NOA HL network which is open: https://data.crosscite.org/application/vnd.datacite.datacite+json/10.7914/SN/HL

**Comment by jschaeff** [comment]
The system just needs to check that rightsList is not empty.

Empty rightsList is a problem even for closed networks.

The best practices are to declare a licence, even for closed networks, along a date of validity of the licence, but we do not need to check on this for now.

**Comment by vpet98** [comment]
Ok, but how can I compare the "restrictionPolicy" of stationXML with the one at datacite? Isn't ensuring that these two are consistent one of the tests?

**Comment by jschaeff** [comment]
You're right there is no way to be categorical programmatically.

Let's make the following assumption  that the test is valid at the date it is launched.

As some consistency checks are complex combinations of conditions, you could modelize each properties of a network and then compare them.

For instance here, you would have the following properties:

net.open [boolean]
net.datacite_rights [list]
net.datacite_availability [date] 
net.datacite_available [boolean] which is 
- len(net.datacite_rigthsList) > 0 and net.datacite_availability <= now 

Then consistent state would be one of those:
- not net.open and not net.datacite_available
or 
- net.open and net.datacite_available

**Comment by jschaeff** [comment]
For reference, there is the documentation of datacite: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/dateType/#available
