### ISSUE TITLE
Create containers for the application

### ISSUE THREAD

**Issue by jschaeff** [EIDA/find-net-board#4]
Create github actions for creating and publishing the container

**Comment by vpet98** [comment]
I have some issues in creating docker containers:
- in order for the docker container to be able to see the local database, the latter must be configured in a way that can be accessed by outer IPs (or at least the IP that the system belongs to). I am wondering if this is ideal?
- some things like creating the admin user need interaction with the user and I am not sure how this can be done from within a docker container.

**Comment by vpet98** [comment]
Do we have an update on what is the best practice to create an admin user with credentials for the application? Right now I use a command into the Dockerfile for this purpose, but seems bad idea to show the credentials there. Other choice would be to have the one who is going to install the application do it manually, but this makes the process less automatic.

**Comment by vpet98** [comment]
Also, I am accessing the database through the dockerfile to run migrate in case of database changes. This makes it not possible to use github workflows to build the docker container.

**Comment by jschaeff** [comment]
The database migration will be up to the deployment process. Do not bother about it.

The same goes for the admin account creation.
